version: '3'
services:
  frontend:
    build:
      context: ./frontend
    expose:
      - 80
    ports:
      - "80:80"
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    tty: true
  backend:
    build:
      context: ./backend
    depends_on:
     - db
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    tty: true
    links:
      - db
  db:
    image: postgres:14.1-alpine
    container_name: db
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local